// components/ImageTile.tsx
import Image from "next/image";


type ImageTileProps = {
  title?: string;
  imgPath: string;
  key?: string;
  url?: string;
};

const ImageTile = ({title, imgPath, key, url}: ImageTileProps) => {
  return (
    <a href={`${url ?? "/#"}`}>
      <div className="flex flex-col h-64 bg-gray-900 justify-center items-center">
        <img
          src={imgPath}
          alt=""
          className="h-full object-cover overflow-hidden opacity-40"
          loading="lazy"
          // height={325.5}
          // aspectRatio={2}
          // fit="cover"
          // position="centre"
          // format="avif"
          // quality={50}
        />
        <span className="flex absolute text-white">{title}</span>
      </div>
    </a>
  );
};

export default ImageTile;

// src/components/ImageTile.svelte
<script lang="ts">
  export let card: any;
</script>

<a href={`/card/${card.code}`} class="block group">
  <div class="aspect-[3/4] rounded-lg overflow-hidden shadow-lg bg-gray-900 transform transition duration-200 group-hover:scale-105 group-hover:shadow-2xl">
    <img
      src={card.fullArtUrl}
      alt={card.name}
      class="object-cover w-full h-full"
      loading="lazy"
    />
  </div>
  <div class="mt-2 text-center">
    <div class="text-white font-semibold truncate">{card.name}</div>
    <div class="text-xs text-gray-400">{card.region} - {card.type} {card.rarity != 'None' ? `- ${card.rarity}` : ''}</div>
  </div>
</a>
